Bundler.require

$yss_file = File.join('data', ENV['YSS'] || 'yss.yml')

task :export do
  $yss = Ferenc::Yss.load($yss_file)
  campaigns = $yss.campaigns
  campaigns.each do |campaign|
    if campaign.valid?
      campaign.display STDOUT
      FileUtils.mkdir_p 'exports'
      FileUtils.chdir 'exports' do
        open("#{campaign.name}.csv", 'w') << campaign.to_csv
      end
    else
      campaign.errors.each do |ad|
        puts ad.keyword.red.bold
      end
    end
  end
end
